### ISSUE TITLE
Segfault

### ISSUE THREAD

**Issue by moiselazarus** [pandom79/Unitd#2]
As soon I run unitcl, it will rise segmentation fault error. I tried a few times
![Screenshot_2022-07-02_16-02-30](https://user-images.githubusercontent.com/5489418/177004220-ef4d135a-92bd-42c6-a1b4-dd8479b6f02c.png)
.

**Comment by pandom79** [comment]
I have no idea. I only can tell you that on my machine and various VM it works.
Could you try to start the system with "**unitd_debug=true**" on the command line ? 
Maybe it could provide more info.

**Comment by pandom79** [comment]
I just installed on Devuan. Also here I had to link sh -> /bin/bash but it works well.


![Screenshot_Devuan_2022-07-02_17:39:13](https://user-images.githubusercontent.com/15945211/177007200-5f388b53-1b76-403e-94eb-f4d0572da67f.png)

**Comment by moiselazarus** [comment]
![Screenshot_2022-07-02_20-07-20](https://user-images.githubusercontent.com/5489418/177011866-f3b3553a-b284-4a29-875f-3fdf1aa9ce03.png)
![Screenshot_2022-07-02_20-02-29](https://user-images.githubusercontent.com/5489418/177011908-44ff8c81-361c-4ebd-9cea-3bbfbbce3e60.png)

**Comment by moiselazarus** [comment]
![Screenshot_2022-07-02_20-14-38](https://user-images.githubusercontent.com/5489418/177012022-7786fdd4-cbd0-4b66-b4a7-43d87ec8cb9a.png)

**Comment by moiselazarus** [comment]
Have you tried unitd with a Musl libc? Any ideas, what can I do?
Maybe because I have lvm, btrfs and cryptsetup. I need a service for activating those?

**Comment by pandom79** [comment]
I think the problem is musl c library related.
The init and final script are taken from void linux which uses musl as well. I would exclude lvm, btrfs etc...
I should have to debug unitd on alpine. Has Alpine an installer for quick installation?

**Comment by moiselazarus** [comment]
https://github.com/alpinelinux/alpine-make-vm-image

**Comment by pandom79** [comment]
Actually, it's not a segfault but unitd receives a SIGBUS signal (Bus error) on this [line](https://github.com/pandom79/Unitd/blob/master/src/core/socket/socket_server.c#L157)
The FD_ISSET musl implementation complains if the first argument is negative.
It should work now.
![Screenshot_alpinelinux3 13_2022-07-03_12:13:50](https://user-images.githubusercontent.com/15945211/177042791-871a376f-3e31-449b-8747-f8278f466d27.png)

Re-download the beta release. I already added the patch.
To be honest, I think that this is a musl bug.
I can understand a different implementation but at least the behaviour should be the same.
Let me know if it worked so that i can close.

**Comment by moiselazarus** [comment]
Thank you!! it's working. Very fast.
![Screenshot_2022-07-03_17-11-59](https://user-images.githubusercontent.com/5489418/177046143-98933d66-0bee-4fda-a859-5600341bbe7b.png)

**Comment by moiselazarus** [comment]
Wow 1,809s
![Screenshot_2022-07-03_17-26-21](https://user-images.githubusercontent.com/5489418/177046468-41e49a15-1a6a-480c-a6f7-5aab7205d243.png)
s

**Comment by pandom79** [comment]
Yeah, finally!!
I'm glad to hear and see it.
Please note that this is a beta release yet. Whatever bug or other just write here.
I show you my boot time with 36 units on bare metal.
![Screenshot_20220703_183029](https://user-images.githubusercontent.com/15945211/177048884-8f115fdc-1cb4-4ed0-817d-2244917167f5.png)

I'm waiting for you confirm to close this issue.

**Comment by moiselazarus** [comment]
really fast! I write my units and test further, I'll also test it on bare metal.
